- docs/README.md
ref: 
- https://github.com/taikochain/taiko-client/pull/21
- https://github.com/taikochain/taiko-mono/pull/195
> [docs] allow `block.timestamp` >= `parent.timestamp`

- driver/block_inserter.go
- version/verison.go
Will let us to use a general pre-generated L2 throwaway builder private key for all testnet users.
> feat(driver): use fixed pre-state for throwaway blocks

- go.mod
Since our `taiko-geth` repo is based on geth v1.10.26, so update the version in this repo's `go.mod` accordingly.
> chore(go.mod): update `go.mod`

- prover/prover.go
when LatestVerifiedId 0, set l1Current to stateVars.GenesisHeight instead start over
> feat(prover): initL1Current from genesisHeight

- go.mod
- go.sum
gohashtree 0.0.1-alpha was preventing build on Aarch64
Dependencies upgraded:
- klauspost/cpuid/v2 (v2.0.14 to v2.2.4)
- prysmaticlabs/gohashtree (v0.0.1-alpha.0.20220303211031-f753e083138c to v0.0.3-alpha)
- golang.org/x/sys (v0.4.0 to v0.7.0)
> chore(deps): upgrade `gohashtree`

- prover/proof_producer/oracle_proof_producer.go
- prover/prover.go
see: https://github.com/taikoxyz/taiko-mono/pull/13673#discussion_r1181035538
> feat(prover): add oracle proof submission delay

- .github/workflows/docker.yml
- cmd/flags/prover.go
- prover/proof_producer/oracle_proof_producer.go
- prover/proof_producer/oracle_proof_producer_test.go
- prover/proof_submitter/util.go
- prover/proof_submitter/valid_proof_submitter.go
- prover/prover.go
- change `OracleProverPrivateKey` to a string flag
- only use first 64 bytes of `zkProof` as `evidence.Proof`
> fix(prover): fix some oracle proof submission issues

- .github/workflows/docker.yml
- cmd/flags/driver.go
- driver/config.go
- driver/config_test.go
- driver/driver.go
- proposer/proposer.go
- prover/proof_producer/proof_producer.go
- prover/proof_producer/zkevm_rpcd_producer.go
- prover/proof_submitter/valid_proof_submitter.go
ref: https://github.com/taikoxyz/zkevm-chain/pull/5
> feat(prover): update `ZkevmRpcdProducer` to integrate new circuits

- .github/workflows/docker.yml
- cmd/flags/proposer.go
- proposer/config.go
- proposer/proposer.go
If we want to change the geth codebase as less as possible, we can do this. or @cyberhorsey u think changing the geth codebase will be a better option?
> feat(proposer): add a `--minimalBlockGasLimit` flag to mitigate the potential gas estimation issue

- prover/proof_producer/zkevm_rpcd_producer.go
- prover/proof_producer/zkevm_rpcd_producer_test.go
- prover/prover.go
ref: https://github.com/taikoxyz/zkevm-chain/pull/5/commits/551f3d8489b0db8213e680052f96e699590ce5db
> feat(proof_producer): update request parameters based on new circuits changes

- go.mod
- go.sum
- proposer/proposer.go
- testutils/helper.go
- testutils/interfaces.go
Cherry pick this feature from A2 branch into main, in case we might still need it for A3 (or later testnets).
> feat(proposer): propose multiple L2 blocks in one L1 block

- driver/chain_syncer/calldata/syncer.go
- driver/chain_syncer/calldata/syncer_test.go
- driver/driver.go
- pkg/chain_iterator/block_batch_iterator.go
- pkg/rpc/dial.go
Since there is no "invalid block" in protocol, we need to retry the block insertion each time there is an error.
> feat(driver): optimize error handling for `CalldataSyncer`

- driver/state/state.go
- metrics/metrics.go
would be handy to be able to see this as a time series instead of a constant latest value on status page.
> feat(driver): add proof reward metric

- driver/driver.go
- driver/driver_test.go
- pkg/rpc/engine.go
- pkg/rpc/engine_test.go
By on interval calling ExchangeTransitionConfigurationV1 through the engine, lastTransitionUpdate gets updated and the beacon warning is consequently never triggered. Default TransitionConfiguration used according to [execution api specs](https://github.com/ethereum/execution-apis/blob/main/src/engine/paris.md)
> feat(all): disable no beacon client seen warning 

- driver/chain_syncer/beaconsync/syncer.go
- driver/chain_syncer/chain_syncer.go
- driver/chain_syncer/chain_syncer_test.go
revert some changes in #288 #289
> fix(driver): fix geth lag to verified block when syncing

- driver/chain_syncer/beaconsync/syncer.go
This may make node unable to start inserting pending blocks
> fix(driver): fix a P2P sync issue

- prover/prover.go
if parentGasUsed and parentHash are correct, but blockHash is incorrect, generate an oracle proof and skip the current `proofWindowExpired` check.
also include 3 general fixes:
-  we were not checking blockHash before when checking isValidProof before cancelling proof generation even for regular provers, so fixed that.
- we should remove the block from `p.currentBlocksWaitingForProofWindow` in prover regardless of what happens after the proof window expires, right now it was only in one conditional block, which would lead to the map growing very large unnecessarily and checking too many blocks. we should also compare block hash here.
- was passing in l2BlockId instead of l1Height to `p.proveNotify` when checking expired windows
> feat(prover): generate an oracle proof if incoming proof is incorrect

- cmd/flags/prover.go
- prover/config.go
- prover/config_test.go
- prover/prover.go
- prover/prover_test.go
this pr adds a flag to the prover, which can determien whether this prover should prove unasigned proofs or not.
unassigned proofs: 
1) one where the proofWindow expires and the assignedprover did not submit a proof on time
2) one where the protocol was out of capacity, and the assignedprover is address(0), which means anyone can submit proof.
This can be useful because if you are proving an unassigned proof, and you get assigned a proof, you will not start generating it until the expired proof is done if you are at proving capacity, and you may potentially be slashed if you are late delivering the proof. So you may want to configure two provers on two different machines, one set to true, one set to false, to ensure you have a prover always working on your assigned proofs.
Also improves …
> feat(prover): flag for proving unassigned proofs or not

- cmd/flags/prover.go
make it a camel-case like other flags
> feat(cmd): update `proveUnassignedBlocks` flag name

- pkg/rpc/client.go
- pkg/rpc/methods.go
- pkg/rpc/utils.go
- proposer/proposer.go
Found that even with our own Sepolia archive node, current `IsArchiveNode` check will fail.
> feat(pkg): improve archive node check

- prover/proof_submitter/util.go
This pull request just replaces 🤷‍♂️ with 🤷 in the log messages.
Depending on the environment, 🤷‍♂️ is not displayed properly because it consists of 4 code points.
| Code point | Character | Name |
| :---: | :---: | :---: |
|  U+1F937 | 🤷 | Shrug |
| U+200D | | Zero Width Joiner (ZWJ) |
| U+2642 | ♂ | Male Sign |
| U+FE0F | ◌️ | Variation Selector-16 (VS16) |
On iTerm2 on macOS, it is displayed as `🤷\u200d♂️`.
From the perspective of gender equality, it would be better to use the neutral one.
> chore(prover): replace emoji in log message

- prover/proof_submitter/util.go
We should not return an error when hitting the `maxRetry` （`--proofSubmissionMaxRetry`） config, otherwise, it will still be retried by the main proof submission loop, and `--proofSubmissionMaxRetry` flag wont work:
> fix(prover): fix `maxRetry` configuration when submitting proofs

- go.mod
- go.sum
Encountered ARM64 incompatibility issues in the existing dependency versions. Updated the mod/sum file to resolve these issues.
I noticed that updates have already been made in the askja branch, but they have not been merged into the main branch. I am not sure if there is a deeper reason for this.
> chore(deps): upgrade gohashtree for ARM64

- integration_test/nodes/init.sh
Before running make test for the first time, switching directories to run the solc installation script after running pnpm install in the protocol directory of taiko-mono can be cumbersome. This change incorporates that step directly into init.sh for convenience.
Before running the forge deployment during make test, check if the PLONK-specific solc compiler is successfully downloaded
> chore(repo): Add Solc Download Check Suite for PlonkVerifier Compilation

- prover/prover.go
ref: https://github.com/taikoxyz/taiko-client/issues/401
> feat(prover): release capacity when the corresponding local proof generation is canceled

- prover/prover.go
- release capacity in defer, not in backoff retry for submitproof op
- delete block being proven immediately, not in defer
> fix(prover): capacity fix

- prover/capacity_manager/capacity_manager.go
- prover/capacity_manager/capacity_manager_test.go
- prover/prover.go
this also blocks capacity from growing larger than the initial max capacity
> fix(prover): capacity needs to be taken before generating proof

- cmd/flags/prover.go
- prover/capacity_manager/capacity_manager.go
- prover/capacity_manager/capacity_manager_test.go
- prover/config.go
- prover/config_test.go
- prover/prover.go
- prover/server/api.go
- prover/server/server_test.go
- testutils/suite.go
capacity can be released twice if, when submitting a proof, the block becomes verified by someone else (ie: you were just too late to submit).
Because there are too many edge cases with arbitrary capacity, it should be tied to a block ID, and only be able to be released once for a given block.
> feat(prover): tie capacity to a specific block id

- pkg/rpc/utils.go
- prover/prover.go
If there is a `transition` in protocol with same `blockHash`, then there is no need to generate a proof again.
> feat(prover): check `transition.blockHash` before proof generation

- .github/workflows/docker.yml
- driver/chain_syncer/calldata/syncer.go
- prover/prover.go
Add another 12 seconds, to ensure another L1 block will be mined before the proof submission
> feat(prover): increase the assignment expiration waiting time

- bindings/encoding/input_test.go
- driver/chain_syncer/beaconsync/progress_tracker.go
- driver/chain_syncer/beaconsync/progress_tracker_test.go
- driver/chain_syncer/beaconsync/syncer.go
- driver/chain_syncer/chain_syncer.go
- driver/driver_test.go
- driver/state/l1_current.go
- driver/state/l1_current_test.go
- driver/state/state.go
- driver/state/state_test.go
- pkg/rpc/ethclient_test.go
- pkg/rpc/utils.go
- proposer/proposer_test.go
- proposer/prover_selector/eth_fee_eoa_selector.go
- proposer/prover_selector/eth_fee_eoa_selector_test.go
- prover/proof_producer/dummty_producer_test.go
- prover/proof_producer/guardian_producer_test.go
- prover/proof_producer/optimistic_producer_test.go
- prover/proof_producer/sgx_producer_test.go
- prover/proof_producer/zkevm_rpcd_producer_test.go
- prover/proof_submitter/proof_contester_test.go
- prover/proof_submitter/proof_submitter_test.go
- prover/proof_submitter/transaction/builder_test.go
- prover/proof_submitter/transaction/sender_test.go
- prover/prover.go
- prover/prover_test.go
Increased code coverage to 60%+
> test(all): add more tests

- cmd/flags/proposer.go
- driver/chain_syncer/calldata/syncer_test.go
- driver/chain_syncer/chain_syncer_test.go
- driver/driver_test.go
- proposer/config.go
- proposer/config_test.go
- proposer/proposer_test.go
- prover/proof_submitter/proof_submitter_test.go
- prover/prover_test.go
> feat(proposer): remove `--l2.suggestedFeeRecipient` flag

- prover/server/api.go
- prover/server/api_test.go
Those two fields will be used by the new guardian prover dashboard.
> feat(prover): improve `/status` API

- pkg/rpc/fallback.go
Old: https://github.com/ethereum-optimism/optimism/blob/develop/bss-core/drivers/max_priority_fee_fallback.go
New: https://github.com/ethereum-optimism/optimism-legacy/blob/develop/bss-core/drivers/max_priority_fee_fallback.go
> chore(pkg): Update fallback.go - Fix broken link

- prover/prover.go
wait for chain head to have block before trying to sign. THis is perhaps a temporary fix as there should be a secondary mechanism for guardian prover signing blocks, perhaps with its own `blockProposedCh` and own iterators, that way it doesnt exist alongside proving code.
I will do a further PR for a `GuardianProverSigner` struct that embeds in the Prover, and has its own event loop, after the weekend, if we want to go that route.
> fix(prover): Guardian prover sign wait

- prover/prover.go
> fix(prover): wait fix for guardian prover

- .github/workflows/test.yml
- prover/db/db.go
- prover/db/db_test.go
- prover/prover.go
- prover/server/api.go
- prover/server/api_test.go
- prover/server/server.go
key previously used block ID which made it difficult to iterate using the DB iterator, because key prefixes would be like `blockid-1, blockid-100` instead of something like `blockid-1, blockid-2`.
also fixes issue where all block hashes were using `latestBlock`, we now store the block hash as part of the value.
adds a more comprehensive test as well.
> feat(prover): change block signing to use timestamp as key

- pkg/rpc/methods.go
Currently, when L2 execution engine is syncing, proposer logs are like:
```
taiko_client_proposer_1  | INFO [12-05|10:31:57.800] L2 execution engine is syncing           progress="&{SyncProgress:0xc0000d07e0 CurrentBlockID:+1356428 HighestBlockID:+1453513}"
taiko_client_proposer_1  | INFO [12-05|10:32:10.073] L2 execution engine is syncing           progress="&{SyncProgress:0xc0000d0900 CurrentBlockID:+1356428 HighestBlockID:+1453513}"
taiko_client_proposer_1  | INFO [12-05|10:32:22.345] L2 execution engine is syncing           progress="&{SyncProgress:0xc0000d03f0 CurrentBlockID:+1356428 HighestBlockID:+1453517}"
taiko_client_proposer_1  | INFO [12-05|10:32:34.619] L2 execution engine is syncing           progress="&{SyncProgress:0xc00036b710 CurrentBlockID:+1356428 …
```
> feat(proposer): optimze log

- .github/workflows/docker.yml
- prover/prover.go
- prover/prover_test.go
For a prover, we need to both approve allowance for `AssignmentHook` (to propose block) and `TaikoL1` (to prove block)
> fix(prover): fix `--prover.allowance` flag

- prover/db/db.go
- prover/guardian_prover_sender/guardian_prover.go
- prover/prover.go
- prover/prover_test.go
> feat(prover): add more comments to prover package

- pkg/rpc/methods.go
ref: https://github.com/taikoxyz/taiko-mono/pull/15493
> feat(pkg): fix a log issue in `ensureGenesisMatched` && update a config

- prover/prover.go
> feat(prover): increase wait time before sending to `proofWindowExpiredCh` 

- bindings/encoding/input.go
- bindings/encoding/struct.go
This commit should not be merged into `alpha-6` branch, only keep it in `main`.
Ref: https://github.com/taikoxyz/taiko-mono/pull/15498
> feat(bindings): update `AssigmentHook` signing based on protocol updates

- cmd/flags/prover.go
- internal/testutils/helper.go
- prover/config.go
- prover/prover.go
- prover/server/api.go
- prover/server/server.go
- prover/server/server_test.go
And add more comments for prover server APIs.
> feat(prover): add `--prover.minEthBalance` and `--prover.minTaikoTokenBalance` flags

- driver/chain_syncer/blob/syncer.go
- driver/chain_syncer/blob/syncer_test.go
- driver/chain_syncer/chain_syncer.go
- driver/chain_syncer/chain_syncer_test.go
- driver/driver_test.go
- internal/testutils/helper.go
- internal/testutils/interfaces.go
- proposer/proposer_test.go
- prover/event_handler/block_proposed_test.go
- prover/event_handler/transition_proved_test.go
- prover/proof_submitter/proof_submitter_test.go
- prover/prover_test.go
To match the names in our protocol
> refactor(driver): rename `calldataSyncer` to `blobSyncer`

- pkg/rpc/methods.go
- prover/anchor_tx_validator/anchor_tx_validator.go
similar to:https://github.com/ethereum/go-ethereum/pull/27329
string formatting takes time (even if there's nothing to format), and also that the errors.New is optimized away.
> chore(pkg): replace `fmt.Errorf()` with `errors.New()` if no param required

- cmd/flags/prover.go
After #797 all provers guardian or not must have an sgx endpoint, so may as well make it required
> chore(prover): make raiko host endpoint required
